name:                hanabi
version:             0.1.0.0
github:              "githubuser/hanabi"
license:             BSD3
author:              "Filippo Baroni"
maintainer:          ""
copyright:           "2018 Filippo Baroni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hanabi#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- containers
- data-ordlist
- lens
- mtl
- monad-loops
- parallel
- pretty-terminal
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wno-missing-fields

executables:
  show-game-exe:
    main:                ShowGame.hs
    source-dirs:         app/ShowGame
    ghc-options:
    - -O2
    dependencies:
    - hanabi
    - random-shuffle
  average-exe:
    main:                Average.hs
    source-dirs:         app/Average
    ghc-options:
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hanabi
    - random-shuffle

tests:
  hanabi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: []
    dependencies:
    - hanabi
